// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pronostico.DAL;

#nullable disable

namespace Pronostico.DAL.Migrations
{
    [DbContext(typeof(PronosticoSaisonContext))]
    [Migration("20240407203526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pronostico.Objet.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accronyme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.EquipeSaison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("SaisonId");

                    b.ToTable("EquipeSaison");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surnom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.JoueurSaison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.HasIndex("SaisonId");

                    b.ToTable("JoueurSaison");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Journee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaisonId");

                    b.ToTable("Journee");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int>("DateHM")
                        .HasColumnType("int");

                    b.Property<int>("EquipeDomId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeExtId")
                        .HasColumnType("int");

                    b.Property<int?>("JourneeId")
                        .HasColumnType("int");

                    b.Property<string>("TypResultat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeDomId");

                    b.HasIndex("EquipeExtId");

                    b.HasIndex("JourneeId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Saison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DateDebut")
                        .HasColumnType("int");

                    b.Property<int>("DateFin")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Saisons");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.EquipeSaison", b =>
                {
                    b.HasOne("Pronostico.Objet.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pronostico.Objet.Models.Saison", "Saison")
                        .WithMany("Equipes")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Joueur", b =>
                {
                    b.HasOne("Pronostico.Objet.Models.Equipe", "EquipeDeCoeur")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipeDeCoeur");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.JoueurSaison", b =>
                {
                    b.HasOne("Pronostico.Objet.Models.Joueur", "Joueur")
                        .WithMany()
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pronostico.Objet.Models.Saison", "Saison")
                        .WithMany("Joueurs")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Journee", b =>
                {
                    b.HasOne("Pronostico.Objet.Models.Saison", "Saison")
                        .WithMany("Calendrier")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Match", b =>
                {
                    b.HasOne("Pronostico.Objet.Models.Equipe", "EquipeDom")
                        .WithMany()
                        .HasForeignKey("EquipeDomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pronostico.Objet.Models.Equipe", "EquipeExt")
                        .WithMany()
                        .HasForeignKey("EquipeExtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pronostico.Objet.Models.Journee", null)
                        .WithMany("Matchs")
                        .HasForeignKey("JourneeId");

                    b.Navigation("EquipeDom");

                    b.Navigation("EquipeExt");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Journee", b =>
                {
                    b.Navigation("Matchs");
                });

            modelBuilder.Entity("Pronostico.Objet.Models.Saison", b =>
                {
                    b.Navigation("Calendrier");

                    b.Navigation("Equipes");

                    b.Navigation("Joueurs");
                });
#pragma warning restore 612, 618
        }
    }
}
